document.addEventListener("DOMContentLoaded", function() {
    const calculateButton = document.getElementById("calculate");
    const resultElement = document.getElementById("result");

    calculateButton.addEventListener("click", function() {
        const nameInput = document.getElementById("name").value;

        if (nameInput !== "") {
            const luckyMessages = [
                "Congratulations! Today is your day. Your mountain is waiting, so get on your way. Remember that good luck and bad luck are just illusions - they are the creations of your mind. Stay positive, stay optimistic, and good things will happen. You are surrounded by positive energy and good vibes. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. Luck is not chance, it's toil; fortune's expensive smile is earned. Keep your face always toward the sunshine, and shadows will fall behind you. Remember, every morning we are born again. What you do today matters most. So go confidently in the direction of your dreams. Live the life you have imagined.",
                "Luck is a matter of preparation meeting opportunity. Today is your day to dance lightly with life, sing wild songs of adventure, soar your spirit, unfurl your joy. Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. To be a champ, you have to believe in yourself when nobody else will. The best luck of all is the luck you make for yourself. Life is not a problem to be solved, but a reality to be experienced. Your mind is powerful, and when you fill it with positive thoughts, your life will start to change. Good things come to those who believe, better things come to those who are patient, and the best things come to those who never give up.",
                "Your luck is like a lightning bolt; it can strike anywhere, anytime. Every day is a new opportunity to change your life and be happy. You've got to get up every morning with determination if you're going to go to bed with satisfaction. Don't count the days; make the days count. Every accomplishment starts with the decision to try. You are never too old to set another goal or to dream a new dream. A positive attitude causes a chain reaction of positive thoughts, events, and outcomes. It is a catalyst, and it sparks extraordinary results. When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.",
                "Life is what happens when you're busy making other plans. So don't wait for something outside of yourself to make you happy in the future. Think how really precious is the time you have to spend, whether it's at work or with your family. Every minute should be enjoyed and savored. Sometimes you find out what you are supposed to be doing by doing the things you are not supposed to do. Your big opportunity may be right where you are now. Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. The best way to predict the future is to create it. Start where you are. Use what you have. Do what you can.",
                "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. Your luck is simply your own attitude toward life. The more you stay positive, the more good things happen to you. Life is what you make it. So why not make it a beautiful one? Every morning brings new potential, but only if you make the most of it. The only way to do great work is to love what you do. Success is not final, failure is not fatal: it is the courage to continue that counts. Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.",
                "Your life does not get better by chance; it gets better by change. Good things come to people who wait, but better things come to those who go out and get them. There are far, far better things ahead than any we leave behind. Life is either a daring adventure or nothing at all. You are never too old to set another goal or to dream a new dream. The only way to achieve the impossible is to believe it is possible. Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. When you have a dream, you've got to grab it and never let go. Believe that life is worth living and your belief will help create the fact.",
                "Success is not final, failure is not fatal: It is the courage to continue that counts. Believe you can and you're halfway there. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. Do not wait to strike till the iron is hot, but make it hot by striking. In the middle of difficulty lies opportunity. You don't have to be a fantastic hero to do certain things - to compete. You can be just an ordinary chap, sufficiently motivated to reach challenging goals. Never let the fear of striking out keep you from playing the game. It's not whether you get knocked down, it's whether you get up.",
                "In the end, we will remember not the words of our enemies, but the silence of our friends. Your time is limited, don't waste it living someone else's life. Life is what happens when you're busy making other plans. The best way to predict the future is to create it. Success is not final, failure is not fatal: It is the courage to continue that counts. Believe you can and you're halfway there. The only way to do great work is to love what you do. The best way to predict the future is to invent it. Your big opportunity may be right where you are now.",
                "Success is not final, failure is not fatal: It is the courage to continue that counts. You miss 100% of the shots you don't take. Success is not in what you have, but who you are. Don't watch the clock; do what it does. Keep going. The only way to do great work is to love what you do. Do not wait to strike till the iron is hot, but make it hot by striking. A person who never made a mistake never tried anything new. Do what you can, with what you have, where you are. The best way to predict the future is to invent it. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
                "The only way to do great work is to love what you do. Don't cry because it's over, smile because it happened. Success is not final, failure is not fatal: It is the courage to continue that counts. Life is what happens when you're busy making other plans. Believe you can and you're halfway there. The only way to do great work is to love what you do. Don't count the days; make the days count. The best way to predict the future is to create it. Life is what happens when you're busy making other plans.",
                "You miss 100% of the shots you don't take. The best way to predict the future is to create it. Your time is limited, don't waste it living someone else's life. Do not wait to strike till the iron is hot, but make it hot by striking. Success is not final, failure is not fatal: It is the courage to continue that counts. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. Your big opportunity may be right where you are now. Life is what happens when you're busy making other plans.",
                "Today is your lucky day! Embrace the positive energy surrounding you. Believe in your abilities and trust that you are capable of achieving great things. Luck is not just a random occurrence; it is the result of your positive attitude and hard work. Keep your mind open to new opportunities, and you'll find luck in unexpected places. Remember, life is full of surprises, and sometimes the best things come when you least expect them. So, keep your head up, stay confident, and luck will continue to shine upon you.",
                "Luck is like a magnet; it attracts positivity and success into your life. With a determined mind and a hopeful heart, you can conquer any challenge that comes your way. Trust in the journey you are on and believe that everything happens for a reason. Every setback is a setup for a comeback. You are destined for greatness, and luck is simply a reflection of your inner strength and resilience. Embrace the challenges, learn from them, and let your positive energy guide you towards a brighter future.",
                "Congratulations! You are the architect of your own luck. Your thoughts and actions shape your destiny, so stay focused on your goals and keep moving forward. Luck favors the bold, so don't be afraid to take risks and pursue your dreams with passion. Remember, luck is not just a one-time occurrence; it is a continuous flow of positive energy that comes to those who believe in themselves. Stay optimistic, stay determined, and let your unwavering faith in your abilities lead you to the path of success.",
                "You are a magnet for good luck and positive vibes. Your optimistic outlook on life attracts opportunities and opens doors to endless possibilities. Keep your mind sharp, your heart open, and your spirit resilient. Luck is not just about chance; it's about being prepared and seizing the right moment. Stay prepared by working hard, staying true to yourself, and being kind to others. The universe has a way of rewarding those who radiate positivity and kindness. So, continue to spread love and positivity, and watch as luck continues to bless your life abundantly.",
                "Luck is a reflection of your inner energy and mindset. When you radiate positivity, luck naturally gravitates towards you. Remember, challenges are stepping stones to success, and each obstacle you overcome paves the way for more opportunities. Stay persistent, stay positive, and trust the timing of your life. Luck is not bound by time; it is always around you, waiting for the perfect moment to shine. Stay patient, keep believing in yourself, and luck will continue to weave its magic into your life's journey.",
                "Believe in yourself and your abilities, for your belief shapes your reality. Luck is not just a matter of chance; it is a result of your confidence and determination. Embrace challenges as opportunities for growth, and let your resilience be your guiding light. Remember, every setback is a setup for a comeback. Stay focused on your goals, stay positive in the face of adversity, and luck will always find its way to you. Your journey is unique, and every experience, both good and bad, is a part of your story. Embrace them all, and let the magic of luck unfold in your life.",
                "Congratulations! You are a beacon of positivity and a magnet for good luck. Your optimism and resilience make you unstoppable. Remember, luck is not just a matter of chance; it is a reflection of your mindset and attitude. Stay true to yourself, stay determined in your pursuits, and luck will continue to grace your journey. Every challenge you face is an opportunity for growth, and every setback is a setup for a comeback. Trust the process, believe in your abilities, and let the universe work its magic. Your future is bright, and luck is always on your side.",
                "Luck is not something you find; it is something that finds you when you least expect it. Your positive energy and unwavering determination attract luck into your life. Embrace challenges as opportunities to learn and grow, and trust that every experience, whether good or bad, is a stepping stone to your success. Remember, luck favors the brave, so be courageous in your pursuits and believe in your dreams. The universe conspires in your favor, and with every step you take, luck walks beside you. Stay focused, stay confident, and let the magic of luck guide you to greatness.",
                "Today is a reminder that luck is not a random event; it is a reflection of your mindset and actions. Your positive energy and determination create a magnetic force that attracts luck into your life. Embrace challenges as opportunities to shine, and remember that every setback is a setup for a comeback. Stay true to your dreams, stay focused on your goals, and let your passion be your guiding light. Luck is not just a stroke of good fortune; it is a continuous flow of positive energy that surrounds you. Keep believing in yourself, keep working hard, and luck will always find its way to you.",
                "Congratulations! You are a master of your destiny and a magnet for good luck. Your positive attitude and unwavering determination set the stage for incredible opportunities. Remember, luck is not just a random occurrence; it is a reflection of your mindset and actions. Stay focused on your goals, stay resilient in the face of challenges, and let your passion drive you forward. Luck is not bound by time; it is always around you, waiting for the perfect moment to shine. Keep believing in yourself, keep spreading positivity, and watch as luck continues to bless your life abundantly.",
                "You are a shining star in the universe, and luck is your constant companion. Your optimism, determination, and kindness create a powerful aura that attracts positive energy and incredible opportunities. Embrace challenges as stepping stones to greatness, and let your resilience be your guiding light. Luck is not just a matter of chance; it is a reflection of your mindset and actions. Stay focused on your dreams, stay true to your values, and let your unwavering belief in yourself lead the way. The universe conspires in your favor, and with every step you take, luck walks beside you.",
                "Congratulations! Today is a testament to your unwavering spirit and positive energy. Luck is not just a random occurrence; it is a reflection of your mindset and actions. Your determination and resilience create a powerful force that attracts incredible opportunities and positive outcomes. Embrace challenges as opportunities to learn and grow, and remember that every setback is a setup for a comeback. Stay true to yourself, stay focused on your goals, and let your passion be your guiding light. Luck is not bound by time; it is always around you, waiting for the perfect moment to shine. Keep believing in yourself, keep working hard, and luck will always find its way to you.",
                "You are a beacon of positivity, and luck is drawn to you like a magnet. Your optimistic outlook on life and unwavering determination create a powerful force that attracts incredible opportunities and positive outcomes. Embrace challenges as opportunities for growth, and let your resilience be your guiding light. Remember, every setback is a setup for a comeback. Stay focused on your dreams, stay true to your values, and let your unwavering belief in yourself lead the way. The universe conspires in your favor, and with every step you take, luck walks beside you.",
                "Congratulations! Today is a testament to your unwavering spirit and positive energy. Luck is not just a random occurrence; it is a reflection of your mindset and actions. Your determination and resilience create a powerful force that attracts incredible opportunities and positive outcomes. Embrace challenges as opportunities to learn and grow, and remember that every setback is a setup for a comeback. Stay true to yourself, stay focused on your goals, and let your passion be your guiding light. Luck is not bound by time; it is always around you, waiting for the perfect moment to shine. Keep believing in yourself, keep working hard, and luck will always find its way to you.",
                "You are a shining star in the universe, and luck is your constant companion. Your optimism, determination, and kindness create a powerful aura that attracts positive energy and incredible opportunities. Embrace challenges as stepping stones to greatness, and let your resilience be your guiding light. Luck is not just a matter of chance; it is a reflection of your mindset and actions. Stay focused on your dreams, stay true to your values, and let your unwavering belief in yourself lead the way. The universe conspires in your favor, and with every step you take, luck walks beside you.",
                "Congratulations! You are a master of your destiny and a magnet for good luck. Your positive attitude and unwavering determination set the stage for incredible opportunities. Remember, luck is not just a random occurrence; it is a reflection of your mindset and actions. Stay focused on your goals, stay resilient in the face of challenges, and let your passion drive you forward. Luck is not bound by time; it is always around you, waiting for the perfect moment to shine. Keep believing in yourself, keep spreading positivity, and watch as luck continues to bless your life abundantly.",
                "Today is a reminder that luck is not a random event; it is a reflection of your mindset and actions. Your positive energy and determination create a magnetic force that attracts luck into your life. Embrace challenges as opportunities to shine, and remember that every setback is a setup for a comeback. Stay true to your dreams, stay focused on your goals, and let your passion be your guiding light. Luck is not just a stroke of good fortune; it is a continuous flow of positive energy that surrounds you. Keep believing in yourself, keep working hard, and luck will always find its way to you.",
                "You are a magnet for good luck and positive vibes. Your optimistic outlook on life attracts opportunities and opens doors to endless possibilities. Keep your mind sharp, your heart open, and your spirit resilient. Luck is not just about chance; it's about being prepared and seizing the right moment. Stay prepared by working hard, staying true to yourself, and being kind to others. The universe has a way of rewarding those who radiate positivity and kindness. So, continue to spread love and positivity, and watch as luck continues to bless your life abundantly.",
                "Luck is a reflection of your inner energy and mindset. When you radiate positivity, luck naturally gravitates towards you. Remember, challenges are stepping stones to success, and each obstacle you overcome paves the way for more opportunities. Stay persistent, stay positive, and trust the timing of your life. Luck is not bound by time; it is always around you, waiting for the perfect moment to shine. Stay patient, keep believing in yourself, and luck will continue to weave its magic into your life's journey.",
                "Believe in yourself and your abilities, for your belief shapes your reality. Luck is not just a matter of chance; it is a result of your confidence and determination. Embrace challenges as opportunities for growth, and let your resilience be your guiding light. Remember, every setback is a setup for a comeback. Stay focused on your goals, stay positive in the face of adversity, and luck will always find its way to you. Your journey is unique, and every experience, both good and bad, is a part of your story. Embrace them all, and let the magic of luck unfold in your life.",
                "You have the power to create your own luck. Your thoughts, actions, and attitude shape your reality. Stay positive, stay focused, and believe in your abilities. Luck is not just a random event; it is a reflection of your mindset and efforts. Embrace challenges as opportunities to grow stronger, and let your determination guide you. Remember, every setback is a setup for a comeback. Keep moving forward with confidence, and luck will continue to be on your side. Your journey is filled with endless possibilities, so keep believing in yourself, and watch as luck transforms your life."
            ];

            const description = generateRandomLuckyMessage();
            
            function generateRandomLuckyMessage() {
                const randomIndex = Math.floor(Math.random() * luckyMessages.length);
                return luckyMessages[randomIndex];
            }

            // Redirect to ssResult.html with data as URL parameters
            window.location.href = `ftResult.html?name=${nameInput}&description=${encodeURIComponent(description)}`;

        } else {
            resultElement.innerHTML = "Please enter your name.";
        }
    });
});