document.addEventListener("DOMContentLoaded", function() {
    const calculateButton = document.getElementById("calculate");
    const resultElement = document.getElementById("result");
    const nameInput = document.getElementById("name");
    const yearSelect = document.getElementById("year");

    // Generate year options from 1900 to the current year
    const currentYear = new Date().getFullYear();
    for (let year = 1900; year <= currentYear; year++) {
        const option = document.createElement("option");
        option.value = year;
        option.textContent = year;
        yearSelect.appendChild(option);
    }

    calculateButton.addEventListener("click", function() {
        const selectedYear = yearSelect.value;
        const enteredName = nameInput.value;

        if (enteredName === "") {
            resultElement.innerHTML = "Please enter your name.";
            return;
        }

        if (selectedYear !== "") {
            const year = parseInt(selectedYear);
            const zodiacSigns = ["Rat", "Ox", "Tiger", "Rabbit", "Dragon", "Snake", "Horse", "Goat", "Monkey", "Rooster", "Dog", "Pig"];
            const zodiacDescriptions = [
                "People born in the Year of the Rat are known for their intelligence, quick-wit, and resourcefulness. They are highly adaptable and can find solutions to challenges effortlessly. Rats are charming, sociable, and often the life of the party, but they can also be critical and perfectionistic. They have a natural curiosity and are constantly seeking knowledge. In relationships, they are loyal and caring partners, but they can also be possessive. Rats are driven by their goals and are willing to work hard to achieve success. They have a keen eye for opportunities and are skilled at seizing them. While they are generally optimistic, they can sometimes be impulsive and restless, always on the lookout for the next adventure.",
                "Individuals born in the Year of the Ox are known for their determination, reliability, and strong work ethic. They are practical and methodical, approaching tasks with patience and discipline. Oxen are loyal and trustworthy, making them dependable friends and partners. They are deeply rooted in their beliefs and traditions, valuing stability and security. While they may appear reserved, they are steadfast and devoted to their loved ones. Oxen are also known for their intelligence and logical thinking, often finding practical solutions to complex problems. They are not easily swayed by emotions, relying on their practicality to navigate life's challenges. In relationships, they are supportive and nurturing, willing to go to great lengths for the people they care about.",
                "People born in the Year of the Tiger are known for their courage, confidence, and natural leadership abilities. They are adventurous and love to explore new territories, both literally and metaphorically. Tigers are passionate and fiercely determined, never shying away from a challenge. They have a magnetic personality that draws others to them, and they are often the center of attention in social settings. Tigers are independent and value their freedom, refusing to be confined by rules and restrictions. They are also compassionate and protective, especially when it comes to their loved ones. While they can be impulsive and quick-tempered, their enthusiasm and energy are contagious, inspiring those around them.",
                "Individuals born in the Year of the Rabbit are known for their gentleness, kindness, and sensitivity. They are compassionate and empathetic, always ready to lend a listening ear or a helping hand to those in need. Rabbits are elegant and poised, with a natural sense of grace that attracts others to them. They have a strong intuition and can often sense the emotions of people around them. Rabbits value harmony and peace, avoiding conflicts whenever possible. They are diplomatic and tactful, skilled at finding compromises and solutions that benefit everyone involved. In relationships, they are loving and nurturing, creating a warm and secure environment for their partners. While they may appear reserved, they have a playful and creative side that they share with their closest friends and family.",
                "People born in the Year of the Dragon are known for their charisma, confidence, and strong sense of purpose. They are natural leaders who inspire others with their enthusiasm and energy. Dragons are ambitious and willing to take on challenges that others might find daunting. They have a pioneering spirit and are not afraid to blaze their own trails. Dragons are intelligent and insightful, often seeing opportunities where others see obstacles. They are passionate about their beliefs and can be persuasive communicators. In relationships, they are loyal and protective partners, willing to stand by their loved ones no matter what. While they can be perceived as arrogant, their confidence is often well-founded, and they are capable of achieving remarkable success in their endeavors.",
                "Individuals born in the Year of the Snake are known for their intelligence, wisdom, and elegance. They are intuitive and perceptive, often relying on their instincts to make decisions. Snakes are strategic and analytical, able to see the bigger picture and plan for the future. They are persuasive and charming, with the ability to influence others with their words. Snakes are graceful and sophisticated, possessing a natural magnetism that draws people to them. They are also determined and focused, willing to pursue their goals with unwavering dedication. In relationships, they are passionate and romantic partners, capable of deep emotional connections. While they may appear cool and composed on the surface, they have a mysterious and enigmatic quality that intrigues others.",
                "People born in the Year of the Horse are known for their energy, independence, and free-spirited nature. They are adventurous and always on the move, seeking excitement and new experiences. Horses are sociable and outgoing, making friends easily with their charismatic personality. They are optimistic and enthusiastic, approaching life with a sense of humor and a positive attitude. Horses are hardworking and determined, often pursuing multiple interests and projects simultaneously. They value their freedom and independence, refusing to be tied down by responsibilities that limit their mobility. In relationships, they are passionate and romantic partners, but they can also be impulsive and easily bored. Despite their occasional restlessness, they are loyal and caring to those they love.",
                "Individuals born in the Year of the Goat are known for their kindness, gentleness, and artistic talents. They are compassionate and empathetic, always willing to help others and make a difference in the lives of those around them. Goats are creative and imaginative, often expressing themselves through various forms of art and creativity. They have a strong sense of aesthetics and appreciate beauty in all its forms. Goats are sensitive and intuitive, able to pick up on the emotions of others and respond with empathy. They value harmony and peace, avoiding conflicts and confrontations whenever possible. In relationships, they are nurturing and supportive partners, willing to make sacrifices for the happiness of their loved ones. While they may appear passive, they possess a quiet strength and resilience that helps them overcome challenges with grace.",
                "People born in the Year of the Monkey are known for their intelligence, wit, and playful nature. They are curious and adventurous, always eager to explore and learn new things. Monkeys are quick thinkers and problem solvers, able to come up with innovative solutions to complex problems. They have a natural charm and charisma that make them popular in social circles. Monkeys are versatile and adaptable, able to excel in various fields due to their diverse skills and talents. They are lively and entertaining, often the life of the party, bringing joy and laughter wherever they go. In relationships, they are fun-loving and affectionate partners, but they can also be mischievous and unpredictable. Despite their playful demeanor, they are loyal and caring to their loved ones.",
                "Individuals born in the Year of the Rooster are known for their confidence, diligence, and attention to detail. They are hardworking and organized, approaching tasks with precision and efficiency. Roosters are honest and straightforward, never afraid to speak their minds and stand up for what they believe in. They have high standards for themselves and others, valuing excellence and dedication. Roosters are practical and resourceful, often finding practical solutions to challenges that others may overlook. They are also observant and analytical, able to assess situations quickly and make informed decisions. In relationships, they are loyal and committed partners, willing to put in the effort to make their relationships thrive. While they can be perceived as critical, their intentions are usually rooted in a desire for improvement and progress.",
                "People born in the Year of the Dog are known for their loyalty, honesty, and reliability. They are compassionate and caring, always putting the needs of others before their own. Dogs are selfless and devoted, willing to go to great lengths to help those they love. They have a strong sense of justice and fairness, standing up for the rights of others and advocating for equality. Dogs are practical and realistic, approaching life with a grounded attitude and a strong work ethic. They are dependable and trustworthy, making them reliable friends and confidants. In relationships, they are faithful and supportive partners, offering unwavering loyalty and affection. While they can be anxious and worrisome, their caring nature and willingness to help others make them beloved companions.",
                "Individuals born in the Year of the Pig are known for their kindness, generosity, and sincerity. They are honest and straightforward, often wearing their hearts on their sleeves. Pigs are compassionate and empathetic, always willing to lend a helping hand to those in need. They have a gentle and peaceful nature, valuing harmony and avoiding conflicts whenever possible. Pigs are diligent and hardworking, willing to put in the effort to achieve their goals. They are reliable and trustworthy, making them dependable friends and partners. Pigs enjoy the simple pleasures of life and have a great appreciation for beauty and art. In relationships, they are loving and devoted partners, cherishing the bonds they share with their loved ones. Despite their sometimes naive and gullible nature, their sincerity and warmth make them endearing to others."
            ];

            const zodiacIndex = (year - 1900) % 12;
            const zodiacSign = zodiacSigns[zodiacIndex];
            const zodiacDescription = zodiacDescriptions[zodiacIndex];

            // Create the result URL with query parameters
            const resultURL = `czResult.html?name=${encodeURIComponent(enteredName)}&zodiacSign=${encodeURIComponent(zodiacSign)}&zodiacDescription=${encodeURIComponent(zodiacDescription)}`;

            // Redirect to the result page
            window.location.href = resultURL;
        } else {
            resultElement.innerHTML = "Please select your birth year.";
        }
    });
});

